/**
 * Thin wrappers around @geoflow/core for use in the web SPA.
 * Re-exports only what the UI tabs need, with web-friendly types.
 */

export {
  decodeBytes,
  parseStr,
  validate,
  Registry,
  validateFileBytes,
  fixBytes,
  summarizeInfoBytes,
  renderInfo,
  diffFiles,
  renderDiffText,
  diffToSummary,
  isIdentical,
  serialize,
  writeDiggs,
  readDiggs,
  assessQuality,
  AgsTypeFunctions,
  Format,
  Severity,
  buildGeo3DModel,
  renderBoreholeStripSvg,
  geolColor,
  discoverVoxelProperties,
  buildVoxelGrid,
  voxelGridToCsv,
  getVoxelCellLineage,
  parseAscGrid,
  parseXyzPoints,
  sampleTopoAt,
  ThinPlateSurface,
} from '@geoflow/core';

export type {
  ParseOutcome,
  ValidateResult,
  FixResult,
  InfoSummary,
  DiffResult,
  GroupDiff,
  AgsFile,
  AgsGroup,
  AgsHeading,
  AgsRow,
  AgsValue,
  AgsType,
  ConversionReport,
  Diagnostic,
  QualityReport,
  QualityDimension,
  Geo3DModel,
  Borehole3D,
  GeoUnit,
  GeoLayer,
  VoxelProperty,
  VoxelCell,
  VoxelGrid,
  VoxelCellLineage,
  VoxelObsContribution,
  TopoGrid,
  ContactPoint,
  Pt3,
} from '@geoflow/core';
